default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: storage/development.sqlite3
  queue:
    <<: *default
    migrations_paths: db/queue_migrate
    database: storage/development_queue.sqlite3

test:
  primary:
    <<: *default
    database: storage/test.sqlite3
  queue:
    <<: *default
    migrations_paths: db/queue_migrate
    database: storage/test_queue.sqlite3
